#!/bin/sh

export MANAGER_HOME="${MANAGER_HOME:-$PWD}"

if [ ! -e "$MANAGER_HOME" ]
then
    echo "$MANAGER_HOME does not exist" 1>&2
    exit 1
fi

JAR="$MANAGER_HOME/tower4clouds-manager.jar"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    MANAGER_HOME=`cygpath -w "$MANAGER_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

exec java  $JVM_ARGS -jar "$JAR" "$@"
