#!/bin/sh

export DATA2STDOUT_HOME="${DATA2STDOUT_HOME:-$PWD}"

if [ ! -e "$DATA2STDOUT_HOME" ]
then
    echo "$DATA2STDOUT_HOME does not exist" 1>&2
    exit 1
fi

JAR="$DATA2STDOUT_HOME/tower4clouds-data2stdout.jar"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    DATA2STDOUT_HOME=`cygpath -w "$DATA2STDOUT_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

exec java  $JVM_ARGS -jar "$JAR" "$@"
